language: objective-c
osx_image: xcode8
xcode_sdk: iphonesimulator9.2
xcode_workspace: SwiftDecimalNumber.xcworkspace
xcode_scheme: SwiftDecimalNumber
rvm:
  - 2.2.2
before_install:
  - gem install bundler
install:
  - bundle
  - bundle exec pod repo update
  - bundle exec pod install
script:
  - xcodebuild test -workspace SwiftDecimalNumber.xcworkspace -scheme SwiftDecimalNumber -destination 'name=iPhone 6'
  - bundle exec pod lib lint
  - scripts/deploy.sh
