language: swift
osx_image: xcode8
rvm:
  - 2.2.2
before_install:
  - gem install bundler
install:
  - bundle
  - bundle exec pod install
script:
  - xcodebuild test -workspace SwiftDecimalNumber.xcworkspace -scheme SwiftDecimalNumber -destination 'name=iPhone 6'
  - bundle exec pod lib lint
  - bundle exec pod spec lint
after_success:
  - bundle exec pod trunk push SwiftDecimalNumber.podspec
