os: osx
osx_image: xcode8
xcode_sdk: iphonesimulator9.2
xcode_workspace: SwiftDecimalNumber.xcworkspace
xcode_scheme: SwiftDecimalNumber
rvm:
  - 2.2.2
before_install:
  - gem install bundler
install:
  - bundle
  - bundle exec pod install
script:
  - bundle exec pod lib lint
  - bundle exec pod spec lint
after_success:
  - bundle exec pod trunk push SwiftDecimalNumber.podspec
